INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Ted', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Behimar', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Miriam', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Arnold', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Jonas', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Roberto', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Pedro', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Gary', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES('Cesar', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Karen', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Deysi', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Claudia', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Samanta', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Carlos', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Charlie', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Ivan', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Jorge', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Paul', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Uriel', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Gabriel', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Thiago', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Santiago', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'Richard', 'Carrasco', 'ted_cc@hotmail.com', '2018-08-16', '');
INSERT INTO clientes(nombre, apellido, email, created_at, foto) VALUES( 'John', 'Alvarado', 'as@hotmail.com', '2018-08-16', '');
